# Generated by Django 5.1.4 on 2025-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
